### ISSUE TITLE
How to login to my SPXP.space-account?

### ISSUE THREAD

**Issue by forenta** [spxp/spxp-specs#10]
Sorry for asking here as I found no other support forum for Hey Folks. Maybe you'd like to create a Lemmy-community for user-support?

I was able to use *Hey Folks* without an account. Now I created an account succesfully. But after that... where's the login-button?

**Comment by mwiesen** [comment]
Hi @forenta. There is no login button. The SPXP protocol specifies that a profile has a public private key pair. This key pair is generated by the HeyFolks app for your profile automatically. If you use the HeyFolks app "just" to read and follow other profiles, you don't even need it. But if you want to write your own posts, it's used to sign your post so that it
* can not be altered
* can be uniquely associated with your profile

Please know that the HeyFolks app stores the private key of your key pair in a secure place in the OS. For example on iOS this is the Security Enclave.

Also, please note that - while the HeyFolks app can read from Mastodon (Activity Pub), Bluesky and Nostr - it cannot write on those protocols (yet). Natively, it supports the SPXP protocol.
